title: Alpental Community Club
author: Mountainstache
email: board@alpentalcc.org
description: >-
  The official website of the Alpental Community Club
baseurl: "" # the subpath of your site, e.g. /blog
url: "alpentalcc.org" # your site's origin, e.g. https://forestry.io
favicon:

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
